### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by 2ndHouse** [Phanx/AnyFavoriteMount#8]
Seeing this error the past couple of nights, not sure if it just happens when joining a raid or not. I'm also using MountMe along with this addon...

[ADDON_ACTION_BLOCKED] AddOn 'AnyFavoriteMount' tried to call the protected function 'CompactRaidFrame1:Show()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: in function `Show'
FrameXML\CompactUnitFrame.lua:330: in function`CompactUnitFrame_UpdateVisible'
FrameXML\CompactUnitFrame.lua:280: in function `CompactUnitFrame_UpdateAll'
FrameXML\CompactUnitFrame.lua:115: in function <FrameXML\CompactUnitFrame.lua:51>

**Comment by Phanx** [comment]
It's probably an interaction with another addon (and not MountMe) since I've never seen any such error, and while AFM does (unavoidably) taint a bunch of stuff, none of that stuff has anything to do with raid frames. If you can come with some kind of reliable test case (eg. make it happen with only AFM and Addon X) and provide a taint log (type `/console taintlog 2`, reload the UI, make it happen, grab the Logs/taint.log file out of your WoW folder) I can see if there's anything to be done, but it's unlikely.

There's really no way to do what AFM does without either (a) overwriting WoW API functions and causing taint or (b) replacing every part of the default UI that calls mount-related API functions so they can't call the real ones. I opted for (a) beacuse it's a lot easier to do, and because (b) wouldn't affect addons, so you'd end up with inconsistent behavior if you were using any other mount-related addons that didn't specifically add support for AFM.
